-- Migration number: 0001 	 2024-06-21T15:38:33.155Z
-- Autogenerated from a schema SQL file using `npx wrangler d1 migrations create`.
--
-- Steps:
-- 1. Create the `product_labels` table
-- 2. (Optional) Remove this comment section

-- Table for product labels (e.g., Difficulty, Product Type)
CREATE TABLE product_labels (
    id TEXT PRIMARY KEY,
    tenant_id TEXT NOT NULL,
    name TEXT NOT NULL,
    category TEXT NOT NULL CHECK(category IN ('difficulty', 'productType', 'custom')),
    color TEXT NOT NULL,
    priority INTEGER NOT NULL DEFAULT 1,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (tenant_id) REFERENCES tenants(id)
);
